var ttt = ttt || Object.create(null);

(function(){
var d0c = document;
function removeOld(el) {
    if(el) {
        el.parentElement.removeChild(el);
    }
}
function addBundleJS() {
    //hashes is autogenerated by webpack, should be in html <script> right before this script.
    if(hashes)
    {
        var vendorsSrc = './' + hashes["vendors~main"]["js"];
        var vendors = d0c.createElement("script");
        var oldVendors = d0c.querySelector(`script[src="${vendorsSrc}"]`);
        removeOld(oldVendors);
        var mainSrc = './' + hashes["main"]["js"];
        var main = d0c.createElement("script");
        var oldMain = d0c.querySelector(`script[src="${mainSrc}"]`);
        removeOld(oldMain);
        var mainCss = './' + hashes["main"]["css"];
        if(hashes["main"]["css"])//note: in inject_mode aka DEV mode this will be undefined
        {
            var oldCss = d0c.querySelector(`link[href="${mainCss}"]`);
            removeOld(oldCss);
            var css = d0c.createElement("link");
            css.rel = "stylesheet";
            css.href = mainCss;
            d0c.head.appendChild(css);
        }
        vendors.src = vendorsSrc;
        main.src = mainSrc;
        d0c.body.appendChild(vendors);
        d0c.body.appendChild(main);
    }
}
function check_webgl() {
    try {
        var tempcanvas = d0c.createElement("canvas");
        var gl = tempcanvas.getContext("webgl") || tempcanvas.getContext("experimental-webgl");
        return gl != null && !!window.WebGLRenderingContext;
    }
    catch (e) {
        return false;
    }
};
var nojs = document.getElementById("nojs-cover");
if(nojs){
    nojs.style.display = "none";
}
console.log("run presw.js");
// WebGL
if(!check_webgl()) {
    return;
}

// If we include swhandler.js, this app uses service workers.
if(typeof wait_for_svc_worker_setup === "function") {
    // If zzzz is in URL, delete and skip service worker.
    if(typeof window.location.href === "string" && window.location.href.indexOf("zzzz") !== -1) {
        delete_old_service_workers();
        addBundleJS();
    } else {
        wait_for_svc_worker_setup(0).then(function(rsVal){
            addBundleJS();
        });
    }
} else {
    // No service worker mode
    addBundleJS();
}
})();